FROM couchdb:1.6.1

MAINTAINER Clemens Stolle klaemo@apache.org

# COPY default.ini /usr/local/etc/couchdb/default.ini
# COPY local.ini /usr/local/etc/couchdb/

COPY lucene-proxy.ini /usr/local/etc/couchdb/local.d/
